# Header
menu:
  Home: /
  Archives: /archives
  #简历: /profile
  #About: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud
- category
#- tag
#- archive
thumbnail: false

# Contacts
contacts:
  github: https://github.com/NeilQ
 # twitter: '#'
 # facebook: '#'
 # dribbble: '#'
 # rss: /atom.xml

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
baidu_analytics: true
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
